version: "3.1"

volumes: 
  db:

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: 
      - .env
    volumes: 
      - db:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on: 
      - "database"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - .env
    depends_on: 
      - "server"